name: juego_memoria
description: Juego de memoria con récords

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  confetti: ^0.7.0
  shared_preferences: ^2.2.2   # NUEVA DEPENDENCIA para guardar récords
  path_provider: ^2.1.1  # NUEVA DEPENDENCIA para guardar archivos

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true